---
all:
  hosts:
    beaker-project.osci.io:

  children:
    # zone managed by OSPO/OSCI in the Community Cage project
    osci_zone:
      vars:
        local_nameservers: "{{ osci.dns }}"
      hosts:
        beaker-project.osci.io:

