---

- name: "Install root ssh keys"
  authorized_key:
    user: root
    key: "{{ item }}"
  loop: "{{ ssh.used_keys }}"

- name: "Remove old root ssh keys"
  authorized_key:
    user: root
    key: "{{ item }}"
    state: absent
  loop: "{{ ssh.revoked_keys }}"

